### ISSUE TITLE
How do I parse dates?

### ISSUE THREAD

**Issue by ghost** [creditdatamw/zerocell#14]
I tried with both LocalDate, and a custom converter, combined with both bare text cells, and cells with  date format, and I get a `null` in all cases.

**Comment by zikani03** [comment]
Hello @yassineim, you should be able to use a custom converter. Perhaps you can give an example of the converter you are using?

I have attached a file with some implementations of custom converter with different date formats.

[DateFormatters.txt](https://github.com/creditdatamw/zerocell/files/3890603/DateFormatters.txt)

**Comment by ghost** [comment]
Thank you very much for the examples.
I realized just now that the class was not `public`, which made it
impossible to instantiate. Now it's working fine.
Thanks again!
