### ISSUE TITLE
Upgrade poi to 5.1.0

### ISSUE THREAD

**Issue by sskorol** [creditdatamw/zerocell#25]
Hi @zikani03,

I want to integrate your library into [test-data-supplier](https://github.com/sskorol/test-data-supplier) I own. The main problem which prevents me from doing it is the poi dependency which doesn't support Java 9+ modules yet. The good news is that they have recently added such support in 5.1.0 version. Wondering if you can make a new release with poi 5.1.0?

Note that I've already tested it locally. And it works as expected.

**Comment by mr-possible** [comment]
But does that mean, the guys who are using Java 8 in their projects will face some error ?

**Comment by tsotsi116** [comment]
Apache POI version 5.1.0 did introduce some breaking changes to the way it reads files. There are multiple ways to resolve the issue.

1.  You can manually change Apache poi version back to 5.0.0 in the root [pom.xml](https://github.com/creditdatamw/zerocell/blob/90a33370069a29054058091be26a5f3e0eb22814/pom.xml#L29) file
2. Clone and install the repository on this commit [c5e9499](https://github.com/creditdatamw/zerocell/commit/c5e94995f197711a44023b9e4f4c9375720c9eaa). Build your application referencing it.
3. Add log4j2 as a dependency in your project
```xml
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.19.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.19.0</version>
        </dependency>
```
