### ISSUE TITLE
Read custom record from excel

### ISSUE THREAD

**Issue by himnay** [creditdatamw/zerocell#6]
Hi,
Is it possible to set the start and end rows to read on a excel sheet. I don't want to read all record.

Regards,
Himansu

**Comment by DaNizz97** [comment]
Hello, Himansu-Nayak
I implemented this ability and opened pull-request. I hope the author will accept these changes.

Best regards,
Daniil

**Comment by zikani03** [comment]
The changes have been merged. You should be able to set start and end rows using a combination of `Reader.skipFirstNRows` and `Reader.setRowNumber`. 
The changes are on the master branch but have not yet been released to central; you may have to clone and build locally.
